FROM eclipse-temurin:21-jre
WORKDIR /data
COPY leaf-26.2-14.jar /app/server.jar
EXPOSE 50013
ENTRYPOINT ["java", "-Xms8G", "-Xmx8G", "-XX:SoftMaxHeapSize=6G", "-XX:+UseZGC", "-XX:+ZGenerational", "-XX:+AlwaysPreTouch", "-XX:+DisableExplicitGC", "-jar", "/app/server.jar", "--nogui"]
