FROM eclipse-temurin:21-jre
WORKDIR /app
COPY velocity-3.5.0-SNAPSHOT-605.jar /app/velocity.jar
EXPOSE 50016
ENTRYPOINT ["java", "-Xms1G", "-Xmx1G", "-XX:+UseZGC", "-XX:+ZGenerational", "-XX:+AlwaysPreTouch", "-XX:+DisableExplicitGC", "-jar", "/app/velocity.jar"]
