FROM eclipse-temurin:21-jre
WORKDIR /data
COPY paper.jar /app/server.jar
EXPOSE 50015
ENTRYPOINT ["java", "-Xms1G", "-Xmx1G", "-XX:SoftMaxHeapSize=700M", "-XX:+UseZGC", "-XX:+ZGenerational", "-XX:+AlwaysPreTouch", "-XX:+DisableExplicitGC", "-jar", "/app/server.jar", "--nogui"]
